#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Called with $1 as the path to poky

set -e
set -u
set -o pipefail
set -x

oecoredir=$(realpath "$1")/layers/openembedded-core/

python3 -m venv venv --without-pip --system-site-packages
source venv/bin/activate
python3 -m pip install -r $oecoredir/meta/lib/patchtest/requirements.txt

$oecoredir/meta/lib/patchtest/selftest/selftest
