#!/usr/bin/env python3
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Read config.py from yocto-autobuilder2 and print the list of supported releases
# for each release.
#
# Usage:
#
#   ./tools/supported-distros --config /path/to/config.py --releases release1 [release2 ...]
#
# Example:
#
#   ./tools/supported-distros --config yocto-autobuilder2/config.py --releases master styhead scarthgap kirkstone
#
# If run with --compare the script with try to run `bitbake-getvar` to obtain the
# value of SANITY_TESTED_DISTROS, and compare that (with some mangling) to the
# configured workers and return 1 in case of difference. Only one release must be
# passed in this mode.
#
# Usage:
#
#    ./tools/supported-distros --config /path/to/config.py --releases master --compare
#
# The opts --release-from-env and --config-from-web can also be used to get
# these info using respectively the LAYERSERIES_COMPAT_core variable and the config.py
# from the git web interface.
#
# Example:
#
#    ./tools/supported-distros --config-from-web --release-from-env --compare
#
# Will get the current release from LAYERSERIES_COMPAT_core, fetch config.py from
# git.yoctoproject.org/yocto-autobuilder2, compare and output the differences.
#
# The script will return 1 in case of difference, 0 if the distros match.
# With one exception: if the branch returned by --release-from-env is not
# present in the autobuilder config, just return 0, because this might by run
# from a custom branch.

import argparse
import json
import os
import re
import sys
import subprocess
import tempfile

from pathlib import Path
from typing import List, Dict, Set

from urllib.error import HTTPError
from urllib.request import Request, urlopen

CONFIG_REMOTE_URL = "https://git.yoctoproject.org/yocto-autobuilder2/plain/config.py"
AUTOBUILDER_WORKERS_ENDPOINT = "https://autobuilder.yoctoproject.org/valkyrie/api/v2/workers"

REQ_HEADERS = {
    "User-Agent": "yocto-autobuilder-helper (git://git.yoctoproject.org/yocto-autobuilder-helper)",
    "Accept": "*/*",
}

INPUT_REGEXES = {
    "alma": {
        "ab": re.compile(r"^alma(\d+)"),
        "lsb": re.compile(r"^almalinux-(\d+)"),
    },
    "debian": {
        "ab": re.compile(r"^debian(\d+)"),
        "lsb": re.compile(r"^debian-(\d+)"),
    },
    "fedora": {
        "ab": re.compile(r"^fedora(\d+)"),
        "lsb": re.compile(r"^fedora-(\d+)"),
    },
    "opensuseleap": {
        "ab": re.compile(r"^opensuse(\d{2})(\d{1})"),
        "lsb": re.compile(r"^opensuse-(\d{2})\.(\d{1})"),
    },
    "centos": {
        "ab": re.compile(r"^centos(\d+)"),
        "lsb": re.compile(r"^centos-(\d+)"),
    },
    "centosstream": {
        "ab": re.compile(r"^stream(\d+)"),
        "lsb": re.compile(r"^stream-(\d+)"),
    },
    "rocky": {
        "ab": re.compile(r"^rocky(\d+)"),
        "lsb": re.compile(r"^rocky-(\d+)"),
    },
    "ubuntu": {
        "ab": re.compile(r"^ubuntu(\d{2})(\d{2})"),
        "lsb": re.compile(r"^ubuntu-(\d{2})\.(\d{2})"),
    },
}

OUTPUT_FORMATS = {
    "alma": {
        "lsb": "almalinux-{}",
        "docs": "-  AlmaLinux {}",
    },
    "debian": {
        "lsb": "debian-{}",
        "docs": "-  Debian {}",
    },
    "fedora": {
        "lsb": "fedora-{}",
        "docs": "-  Fedora {}",
    },
    "opensuseleap": {
        "lsb": "opensuseleap-{}.{}",
        "docs": "-  OpenSUSE Leap {}.{}",
    },
    "centos": {
        "lsb": "centos-{}",
        "docs": "-  CentOS {}",
    },
    "centosstream": {
        "lsb": "centosstream-{}",
        "docs": "-  CentOS Stream {}",
    },
    "rocky": {
        "lsb": "rocky-{}",
        "docs": "-  Rocky Linux {}",
    },
    "ubuntu": {
        "lsb": "ubuntu-{}.{}",
        "docs": "-  Ubuntu {}.{}",
    },
}


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Print supported distributions")

    g1 = parser.add_mutually_exclusive_group()

    g1.add_argument("--release",
                    type=str,
                    help="Yocto release (master, walnascar, ...)")

    g1.add_argument("--release-from-env",
                    action="store_true",
                    help="Get the release codename from the bitbake environment")

    g2 = parser.add_mutually_exclusive_group()

    g2.add_argument("--config",
                    type=Path,
                    default=None,
                    help="Autobuilder config.py input file")

    g2.add_argument("--config-from-web",
                    action="store_true",
                    help="Get config.py from yoctoproject's git web interface")

    g3 = parser.add_mutually_exclusive_group()

    g3.add_argument("--compare",
                    action="store_true",
                    help="Compare to poky.conf releases")

    g3.add_argument("--poky-distros",
                    action="store_true",
                    help="Print previously tested distros")

    g3.add_argument("--old-distros",
                    action="store_true",
                    help="Print previously tested distros")

    parser.add_argument("--check-worker-statuses",
                        action="store_true",
                        default=False,
                        help="Also check the worker statuses using the Autobuilder API")

    parser.add_argument("--output-format",
                        type=str,
                        default="lsb",
                        choices=['lsb', 'docs'],
                        help="Output format of the workers ('lsb' or 'docs')")

    return parser.parse_args()


def _possible_workers(all_workers: List[str],
                      match_workers: List[str]) -> List[str]:
    """
    Return workers in match_workers that match the workers in all_workers.
    A match is a worker in all_workers that starts with a worker in
    match_workers.
    This is because workers_prev_releases is defined like so in config.py.
    """

    possible_workers = []
    for distro_name in all_workers:
        for worker in match_workers:
            if worker.startswith(distro_name):
                possible_workers.append(worker)
    return possible_workers


def _print_worker_list(worker_list: List):
    """
    Helper to print a set nicely.
    """
    for w in worker_list:
        print(w)


def _print_worker_list_warning(worker_list: List, warning):
    """
    Helper to print a warning nicely.
    """
    for w in worker_list:
        print("WARNING: " + warning + ": " + w)


def _print_workers(release: str, possible_workers: List[str]):
    """
    Helper to print the workers nicely.
    """
    _print_worker_list(sorted(possible_workers))


def _get_poky_distros() -> Set[str]:
    poky_distros = set()

    tested_distros = subprocess.check_output(
        ["bitbake-getvar", "--quiet", "--value", "SANITY_TESTED_DISTROS"],
        encoding="utf-8")
    tested_distros = tested_distros.replace("\\n", "")

    for distro in tested_distros.split():
        if "poky" in distro:
            continue

        if "almalinux" in distro:
            # remove the minor version string
            r = re.compile(r"^(almalinux-\d+)\.\d+")
            m = re.match(r, distro)
            if m:
                distro = m.group(1)

        poky_distros.add(distro.strip())

    return poky_distros


def _get_current_core_release() -> str:
    """
    Return the current release.
    Try METADATA_BRANCH first since this is the only way for us to know we're on
    master. If we're not on master, return the latest value in LAYERSERIES_COMPAT_core
    """
    release = subprocess.check_output(
        ["bitbake-getvar", "--quiet", "--value", "METADATA_BRANCH"],
        encoding="utf-8")
    release = release.strip()
    if "master" in release:
        return "master"

    release = subprocess.check_output(
        ["bitbake-getvar", "--quiet", "--value", "LAYERSERIES_COMPAT_core"],
        encoding="utf-8")
    return release.strip().split()[-1]


def _mangle_worker(worker: str, format_in: str, format_out: str) -> str:
    """
    Mangle the worker name to convert it to a different format.
    Input -> output formats can be:
    - ab -> lsb
    - ab -> docs
    - lsb -> docs
    """

    if format_in == format_out:
        return worker

    for distro in INPUT_REGEXES:
        m = re.match(INPUT_REGEXES[distro][format_in], worker)
        if m:
            return OUTPUT_FORMATS[distro][format_out].format(*list(m.groups()))

    return ""


def _compare(ab_workers: set, poky_workers: set, stable_release: bool):
    ok = True

    print("Configured on the autobuilder:")
    _print_worker_list(sorted(list(ab_workers)))
    print()

    print("Listed in poky.conf:")
    _print_worker_list(sorted(list(poky_workers)))
    print()

    poky_missing = ab_workers.difference(sorted(list(poky_workers)))
    if poky_missing:
        _print_worker_list_warning(poky_missing, "Missing in poky.conf but configured on the autobuilder")
        print()
        ok = False

    ab_missing = poky_workers.difference(sorted(list(ab_workers)))
    if ab_missing:
        if stable_release:
            print("Missing entries on the autobuilder while listed in poky.conf, "
                  "but comparing for a stable release so ignoring")
        else:
            _print_worker_list_warning(sorted(list(ab_missing)), "Missing on the autobuilder but listed in poky.conf")
            ok = False
        print()

    return ok


def _filter_inactive_workers(possible_workers: List[str]) -> List[str]:
    """
    From the current list of workers, remove the workers that are inactive
    (disconnected) by checking the Autobuilder REST API.
    """

    _possible_workers = []
    workers_ab = []

    req = Request(AUTOBUILDER_WORKERS_ENDPOINT, headers=REQ_HEADERS)

    try:
        with urlopen(req) as r:
            workers_ab = json.load(r).get("workers")
    except (HTTPError, AttributeError) as e:
        print(f"WARNING: Error when trying to fetch the worker statuses from {AUTOBUILDER_WORKERS_ENDPOINT}:")
        print(e)
        print("Safely exiting...")
        exit(0)

    if not workers_ab:
        return possible_workers

    def is_connected(worker):
        for w_info in workers_ab:
            if w_info.get("name") == worker and w_info.get("connected_to"):
                return True

        return False

    _possible_workers = [w for w in possible_workers if is_connected(w)]

    return _possible_workers


def main():

    args = parse_arguments()

    if not args.config and not args.config_from_web:
        print("Must provide path to config or --config-from-web")
        exit(1)

    if args.config_from_web:
        req = Request(CONFIG_REMOTE_URL, headers=REQ_HEADERS)
        try:
            with urlopen(req) as r:
                with tempfile.TemporaryDirectory() as tempdir:
                    with open(Path(tempdir) / "config.py", "wb") as conf:
                        conf.write(r.read())
                    sys.path.append(tempdir)
                    import config
        except HTTPError as e:
            print(f"WARNING: HTTPError when trying to fetch the config.py file from {CONFIG_REMOTE_URL}:")
            print(e)
            print("Safely exiting...")
            exit(0)
    else:
        sys.path.append(os.path.dirname(args.config))
        import config

    release = None
    if args.release_from_env:
        release = _get_current_core_release()
    else:
        release = args.release

    if not release:
        print("Must provide a release, or --release-from-env")
        exit(1)

    possible_workers = []

    stable_release = True

    if release != "master" and release not in config.workers_prev_releases:
        print(f"Release {release} does not exist")
        if args.release_from_env:
            # Might be a custom branch or something else... safely exiting
            exit(0)
        else:
            exit(1)

    if release == "master":
        stable_release = False
        possible_workers = config.all_workers
    else:
        possible_workers = _possible_workers(config.workers_prev_releases[release],
                                             config.all_workers)

    if args.check_worker_statuses:
        possible_workers = _filter_inactive_workers(possible_workers)

    if args.compare:
        print(f"Comparing for release {release}...\n")

        poky_workers = _get_poky_distros()
        ab_workers = set()
        for w in possible_workers:
            mangled_w = _mangle_worker(w, "ab", "lsb")
            if mangled_w:
                ab_workers.add(mangled_w)

        if not _compare(ab_workers, poky_workers, stable_release):
            print("Mismatches were found")
        else:
            print("All good!")

    elif args.poky_distros:
        poky_distros = _get_poky_distros()
        workers = set()
        for w in poky_distros:
            mangled_w = _mangle_worker(w, "lsb", args.output_format)
            if mangled_w:
                workers.add(mangled_w)
        _print_workers(release, workers)

    elif args.old_distros:
        if release == "master":
            print("The --old-distros argument only makes sense for stable release")
            exit(1)

        old_distros = []

        for distro in config.workers_prev_releases[release]:
            if not any(distro in w for w in config.all_workers):
                old_distros.append(_mangle_worker(distro, "ab", args.output_format))

        _print_workers(release, old_distros)

    else:
        workers = set()
        for w in possible_workers:
            mangled_w = _mangle_worker(w, "ab", args.output_format)
            if mangled_w:
                workers.add(mangled_w)
        _print_workers(release, workers)


if __name__ == "__main__":
    main()
